//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Sigim.Application.Resource.Sigim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIR.Sigim.Application.Resource.Sigim.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco usado para carteira !.
        /// </summary>
        public static string BancoCarteira {
            get {
                return ResourceManager.GetString("BancoCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operações anteriores a data de {0} não poderão ser realizadas, pois foi cadastrado um bloqueio contábil para o centro de custo {1}..
        /// </summary>
        public static string BloqueioContabilEncontrado {
            get {
                return ResourceManager.GetString("BloqueioContabilEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0}  não é válido..
        /// </summary>
        public static string CampoInvalido {
            get {
                return ResourceManager.GetString("CampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave de acesso não informada. Entre em contato com a GIR !.
        /// </summary>
        public static string ChaveAcessoNaoInformada {
            get {
                return ResourceManager.GetString("ChaveAcessoNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe insumo não cadastrada..
        /// </summary>
        public static string ClasseInsumoNaoCadastrada {
            get {
                return ResourceManager.GetString("ClasseInsumoNaoCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma classe insumo do último nível..
        /// </summary>
        public static string ClasseUltimoNivel {
            get {
                return ResourceManager.GetString("ClasseUltimoNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de expiração não foi informada ou está inválida. Entre em contato com a GIR !.
        /// </summary>
        public static string DataExpiracaoNaoInformada {
            get {
                return ResourceManager.GetString("DataExpiracaoNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de utilização do sistema expirou. Entre em contato com a GIR !.
        /// </summary>
        public static string DataExpirada {
            get {
                return ResourceManager.GetString("DataExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do campo &quot;{0}&quot; está maior que a data do campo &quot;{1}&quot;..
        /// </summary>
        public static string DataMaiorQue {
            get {
                return ResourceManager.GetString("DataMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data máxima não pode ser menor que a data mínima..
        /// </summary>
        public static string DataMaximaMenorQueMinima {
            get {
                return ResourceManager.GetString("DataMaximaMenorQueMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data mínima não pode ser maior que a data máxima..
        /// </summary>
        public static string DataMinimaMaiorQueMaxima {
            get {
                return ResourceManager.GetString("DataMinimaMaiorQueMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira um endereço de email válido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado. Entre em contato com a GIR !.
        /// </summary>
        public static string ErroAcessoLogGirCliente {
            get {
                return ResourceManager.GetString("ErroAcessoLogGirCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao efetuar a exclusão !.
        /// </summary>
        public static string ExclusaoErro {
            get {
                return ResourceManager.GetString("ExclusaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem deve ter um dos seguintes formatos: BMP, JPG, GIF ou PNG..
        /// </summary>
        public static string FormatoImagemInvalido {
            get {
                return ResourceManager.GetString("FormatoImagemInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao efetuar a gravação !.
        /// </summary>
        public static string GravacaoErro {
            get {
                return ResourceManager.GetString("GravacaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações não encontradas !.
        /// </summary>
        public static string InformacaoNaoEncontrada {
            get {
                return ResourceManager.GetString("InformacaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma data válida..
        /// </summary>
        public static string InformeDataValida {
            get {
                return ResourceManager.GetString("InformeDataValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite máximo de {1} caracteres excedido..
        /// </summary>
        public static string LimiteMaximoCaracteresExcedido {
            get {
                return ResourceManager.GetString("LimiteMaximoCaracteresExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo com no mínimo {1} caracteres..
        /// </summary>
        public static string LimiteMinimoCaracteresNaoAtingido {
            get {
                return ResourceManager.GetString("LimiteMinimoCaracteresNaoAtingido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse módulo não faz parte do seu pacote..
        /// </summary>
        public static string ModuloNaoPermitido {
            get {
                return ResourceManager.GetString("ModuloNaoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem registros..
        /// </summary>
        public static string NaoExistemRegistros {
            get {
                return ResourceManager.GetString("NaoExistemRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        public static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilégios insuficientes para executar esta operação..
        /// </summary>
        public static string PrivilegiosInsuficientes {
            get {
                return ResourceManager.GetString("PrivilegiosInsuficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro [{0}] está sendo usado..
        /// </summary>
        public static string RegistroEmUso {
            get {
                return ResourceManager.GetString("RegistroEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o registro..
        /// </summary>
        public static string RegistroNaoRecuperado {
            get {
                return ResourceManager.GetString("RegistroNaoRecuperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro [{0}] está protegido..
        /// </summary>
        public static string RegistroProtegido {
            get {
                return ResourceManager.GetString("RegistroProtegido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conversão da cadeia de caracteres no tipo &apos;Date&apos; não é válida..
        /// </summary>
        public static string SistemaBloqueado {
            get {
                return ResourceManager.GetString("SistemaBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha um arquivo com o tamanho menor ou igual a 1 MB..
        /// </summary>
        public static string TamanhoArquivoSuperior1MB {
            get {
                return ResourceManager.GetString("TamanhoArquivoSuperior1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo [{0}] com um valor maior que [{1}]..
        /// </summary>
        public static string ValorDeveSerMaiorQue {
            get {
                return ResourceManager.GetString("ValorDeveSerMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo [{0}] com um valor menor que [{1}]..
        /// </summary>
        public static string ValorDeveSerMenorQue {
            get {
                return ResourceManager.GetString("ValorDeveSerMenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo {0} com um valor numérico..
        /// </summary>
        public static string ValorDeveSerNumerico {
            get {
                return ResourceManager.GetString("ValorDeveSerNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo {0} com um valor numérico e ou espaço..
        /// </summary>
        public static string ValorDeveSerNumericoEOuEspaco {
            get {
                return ResourceManager.GetString("ValorDeveSerNumericoEOuEspaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do campo &quot;{0}&quot; está maior que o valor do campo &quot;{1}&quot;..
        /// </summary>
        public static string ValorMaiorQue {
            get {
                return ResourceManager.GetString("ValorMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão inválida !.
        /// </summary>
        public static string VersaoInvalida {
            get {
                return ResourceManager.GetString("VersaoInvalida", resourceCulture);
            }
        }
    }
}
