//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Sigim.Application.Resource.Sigim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIR.Sigim.Application.Resource.Sigim.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operações anteriores a data de {0} não poderão ser realizadas, pois foi cadastrado um bloqueio contábil para o centro de custo {1}..
        /// </summary>
        public static string BloqueioContabilEncontrado {
            get {
                return ResourceManager.GetString("BloqueioContabilEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0}  não é válido..
        /// </summary>
        public static string CampoInvalido {
            get {
                return ResourceManager.GetString("CampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data máxima não pode ser menor que a data mínima..
        /// </summary>
        public static string DataMaximaMenorQueMinima {
            get {
                return ResourceManager.GetString("DataMaximaMenorQueMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data mínima não pode ser maior que a data máxima..
        /// </summary>
        public static string DataMinimaMaiorQueMaxima {
            get {
                return ResourceManager.GetString("DataMinimaMaiorQueMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira um endereço de email válido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem deve ter um dos seguintes formatos: BMP, JPG, GIF ou PNG..
        /// </summary>
        public static string FormatoImagemInvalido {
            get {
                return ResourceManager.GetString("FormatoImagemInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma data válida..
        /// </summary>
        public static string InformeDataValida {
            get {
                return ResourceManager.GetString("InformeDataValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite máximo de {1} caracteres excedido..
        /// </summary>
        public static string LimiteMaximoCaracteresExcedido {
            get {
                return ResourceManager.GetString("LimiteMaximoCaracteresExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo com no mínimo {1} caracteres..
        /// </summary>
        public static string LimiteMinimoCaracteresNaoAtingido {
            get {
                return ResourceManager.GetString("LimiteMinimoCaracteresNaoAtingido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        public static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro [{0}] está sendo usado..
        /// </summary>
        public static string RegistroEmUso {
            get {
                return ResourceManager.GetString("RegistroEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro [{0}] está protegido..
        /// </summary>
        public static string RegistroProtegido {
            get {
                return ResourceManager.GetString("RegistroProtegido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha um arquivo com o tamanho menor ou igual a 1 MB..
        /// </summary>
        public static string TamanhoArquivoSuperior1MB {
            get {
                return ResourceManager.GetString("TamanhoArquivoSuperior1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo {0} com um valor numérico..
        /// </summary>
        public static string ValorDeveSerNumerico {
            get {
                return ResourceManager.GetString("ValorDeveSerNumerico", resourceCulture);
            }
        }
    }
}
