//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GIR.Sigim.Application.Service.clienteAcessoLogWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="clienteAcessoLogWSSoap", Namespace="http://tempuri.org/")]
    public partial class clienteAcessoLogWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AtualizaAcessoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaAcessoClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public clienteAcessoLogWS() {
            this.Url = global::GIR.Sigim.Application.Service.Properties.Settings.Default.GIR_Sigim_Application_Service_clienteAcessoLogWS_clienteAcessoLogWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AtualizaAcessoClienteCompletedEventHandler AtualizaAcessoClienteCompleted;
        
        /// <remarks/>
        public event ValidaAcessoClienteCompletedEventHandler ValidaAcessoClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtualizaAcessoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AtualizaAcessoCliente(int parIntCodigoCliente, string parStrNomeCliente, string parStrNomeServidor, string parStrIP, string parStrNomeUsuario, string parStrNomeSistema, int parIntContadorUsuario, string parStrNomeBaseDados, string parStrVersaoSistema) {
            object[] results = this.Invoke("AtualizaAcessoCliente", new object[] {
                        parIntCodigoCliente,
                        parStrNomeCliente,
                        parStrNomeServidor,
                        parStrIP,
                        parStrNomeUsuario,
                        parStrNomeSistema,
                        parIntContadorUsuario,
                        parStrNomeBaseDados,
                        parStrVersaoSistema});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizaAcessoClienteAsync(int parIntCodigoCliente, string parStrNomeCliente, string parStrNomeServidor, string parStrIP, string parStrNomeUsuario, string parStrNomeSistema, int parIntContadorUsuario, string parStrNomeBaseDados, string parStrVersaoSistema) {
            this.AtualizaAcessoClienteAsync(parIntCodigoCliente, parStrNomeCliente, parStrNomeServidor, parStrIP, parStrNomeUsuario, parStrNomeSistema, parIntContadorUsuario, parStrNomeBaseDados, parStrVersaoSistema, null);
        }
        
        /// <remarks/>
        public void AtualizaAcessoClienteAsync(int parIntCodigoCliente, string parStrNomeCliente, string parStrNomeServidor, string parStrIP, string parStrNomeUsuario, string parStrNomeSistema, int parIntContadorUsuario, string parStrNomeBaseDados, string parStrVersaoSistema, object userState) {
            if ((this.AtualizaAcessoClienteOperationCompleted == null)) {
                this.AtualizaAcessoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizaAcessoClienteOperationCompleted);
            }
            this.InvokeAsync("AtualizaAcessoCliente", new object[] {
                        parIntCodigoCliente,
                        parStrNomeCliente,
                        parStrNomeServidor,
                        parStrIP,
                        parStrNomeUsuario,
                        parStrNomeSistema,
                        parIntContadorUsuario,
                        parStrNomeBaseDados,
                        parStrVersaoSistema}, this.AtualizaAcessoClienteOperationCompleted, userState);
        }
        
        private void OnAtualizaAcessoClienteOperationCompleted(object arg) {
            if ((this.AtualizaAcessoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizaAcessoClienteCompleted(this, new AtualizaAcessoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaAcessoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaAcessoCliente(int parIntCodigoCliente) {
            object[] results = this.Invoke("ValidaAcessoCliente", new object[] {
                        parIntCodigoCliente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAcessoClienteAsync(int parIntCodigoCliente) {
            this.ValidaAcessoClienteAsync(parIntCodigoCliente, null);
        }
        
        /// <remarks/>
        public void ValidaAcessoClienteAsync(int parIntCodigoCliente, object userState) {
            if ((this.ValidaAcessoClienteOperationCompleted == null)) {
                this.ValidaAcessoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaAcessoClienteOperationCompleted);
            }
            this.InvokeAsync("ValidaAcessoCliente", new object[] {
                        parIntCodigoCliente}, this.ValidaAcessoClienteOperationCompleted, userState);
        }
        
        private void OnValidaAcessoClienteOperationCompleted(object arg) {
            if ((this.ValidaAcessoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaAcessoClienteCompleted(this, new ValidaAcessoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AtualizaAcessoClienteCompletedEventHandler(object sender, AtualizaAcessoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizaAcessoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizaAcessoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ValidaAcessoClienteCompletedEventHandler(object sender, ValidaAcessoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaAcessoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaAcessoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591