//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Sigim.Application.Resource.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIR.Sigim.Application.Resource.Admin.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha e a confirmação não correspondem..
        /// </summary>
        public static string ConfirmacaoNovaSenhaNaoConfere {
            get {
                return ResourceManager.GetString("ConfirmacaoNovaSenhaNaoConfere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione as funcionalidades..
        /// </summary>
        public static string FuncionalidadesNaoMarcadas {
            get {
                return ResourceManager.GetString("FuncionalidadesNaoMarcadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha deve ser diferante da atual..
        /// </summary>
        public static string NovaSenhaIgualAtual {
            get {
                return ResourceManager.GetString("NovaSenhaIgualAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha não pode ser igual ao login..
        /// </summary>
        public static string NovaSenhaIgualLogin {
            get {
                return ResourceManager.GetString("NovaSenhaIgualLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual está incorreta ou a nova senha é inválida..
        /// </summary>
        public static string SenhaAtualIncorreta {
            get {
                return ResourceManager.GetString("SenhaAtualIncorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode conter espaços..
        /// </summary>
        public static string SenhaComEspacos {
            get {
                return ResourceManager.GetString("SenhaComEspacos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 7 caracteres..
        /// </summary>
        public static string SenhaComMenosDeSeteCaracteres {
            get {
                return ResourceManager.GetString("SenhaComMenosDeSeteCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não aceita senha em branco..
        /// </summary>
        public static string SenhaEmBranco {
            get {
                return ResourceManager.GetString("SenhaEmBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha digitada deve possuir no mínimo um dos seguintes caracteres especiais: ! # $ - + ? : ] [ ( ).
        /// </summary>
        public static string SenhaSemCaracterEspecial {
            get {
                return ResourceManager.GetString("SenhaSemCaracterEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha digitada deve possuir no mínimo um caracter alfabético..
        /// </summary>
        public static string SenhaSemLetra {
            get {
                return ResourceManager.GetString("SenhaSemLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha digitada deve possuir no mínimo um caracter númerico..
        /// </summary>
        public static string SenhaSemNumero {
            get {
                return ResourceManager.GetString("SenhaSemNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário e/ou senha inseridos estão incorretos..
        /// </summary>
        public static string UsuarioOuSenhaIncorretos {
            get {
                return ResourceManager.GetString("UsuarioOuSenhaIncorretos", resourceCulture);
            }
        }
    }
}
