//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Sigim.Application.Resource.OrdemCompra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIR.Sigim.Application.Resource.OrdemCompra.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de liberar título(s) para o financeiro, defina a(s) forma(s) de pagamento da EM..
        /// </summary>
        public static string DefinaFormasPagamento {
            get {
                return ResourceManager.GetString("DefinaFormasPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada de Material \&quot;{0}\&quot;..
        /// </summary>
        public static string EntradaMaterialSituacaoInvalida {
            get {
                return ResourceManager.GetString("EntradaMaterialSituacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe(m) forma(s) de pagamento(s) para a ordem de compra do item selecionado..
        /// </summary>
        public static string ExisteFormaPagamentoParaItemSelecionado {
            get {
                return ResourceManager.GetString("ExisteFormaPagamentoParaItemSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de liberar títulos, informe os dados da nota fiscal do frete..
        /// </summary>
        public static string InformeDadosFreteParaLiberacao {
            get {
                return ResourceManager.GetString("InformeDadosFreteParaLiberacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o motivo do cancelamento da Entrada de Material..
        /// </summary>
        public static string InformeMotivoCancelamentoEntradaMaterial {
            get {
                return ResourceManager.GetString("InformeMotivoCancelamentoEntradaMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o motivo do cancelamento da Pré-requisicao..
        /// </summary>
        public static string InformeMotivoCancelamentoPreRequisicao {
            get {
                return ResourceManager.GetString("InformeMotivoCancelamentoPreRequisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o motivo do cancelamento da Requisição..
        /// </summary>
        public static string InformeMotivoCancelamentoRequisicao {
            get {
                return ResourceManager.GetString("InformeMotivoCancelamentoRequisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item {0} já foi aprovado..
        /// </summary>
        public static string ItemJaAprovado {
            get {
                return ResourceManager.GetString("ItemJaAprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operações anteriores a data de &apos;{0}&apos; não poderão ser realizadas, pois foi cadastrado um bloqueio contábil  para o centro de custo &apos;{1}&apos;..
        /// </summary>
        public static string OcorreuBloqueioContabil {
            get {
                return ResourceManager.GetString("OcorreuBloqueioContabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível liberar no financeiro títulos com situação provisionado..
        /// </summary>
        public static string ParaLiberacaoTitulosDevemEstarProvisionados {
            get {
                return ResourceManager.GetString("ParaLiberacaoTitulosDevemEstarProvisionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pré-requisição possui itens e não pode ser cancelada..
        /// </summary>
        public static string PreRequisicaoComItens {
            get {
                return ResourceManager.GetString("PreRequisicaoComItens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pré requisição \&quot;{0}\&quot;..
        /// </summary>
        public static string PreRequisicaoSituacaoInvalida {
            get {
                return ResourceManager.GetString("PreRequisicaoSituacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição com itens não requisitados..
        /// </summary>
        public static string RequisicaoComItensNaoRequisitados {
            get {
                return ResourceManager.GetString("RequisicaoComItensNaoRequisitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição \&quot;{0}\&quot;..
        /// </summary>
        public static string RequisicaoSituacaoInvalida {
            get {
                return ResourceManager.GetString("RequisicaoSituacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma entrada de material..
        /// </summary>
        public static string SelecioneUmaEntradaMaterial {
            get {
                return ResourceManager.GetString("SelecioneUmaEntradaMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos 1 item para aprovação..
        /// </summary>
        public static string SelecioneUmItemParaAprocacao {
            get {
                return ResourceManager.GetString("SelecioneUmItemParaAprocacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título {0}, já está pago..
        /// </summary>
        public static string TituloEstaPago {
            get {
                return ResourceManager.GetString("TituloEstaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título de frete {0}, já está pago..
        /// </summary>
        public static string TituloFreteEstaPago {
            get {
                return ResourceManager.GetString("TituloFreteEstaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título de imposto {0}, já está pago..
        /// </summary>
        public static string TituloImpostoEstaPago {
            get {
                return ResourceManager.GetString("TituloImpostoEstaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores das formas de pagamento da OC diferentes dos valores dos títulos..
        /// </summary>
        public static string ValoresFormaPagamentoDiferenteValoresTituloPagar {
            get {
                return ResourceManager.GetString("ValoresFormaPagamentoDiferenteValoresTituloPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores a liberar para o financeiro diferentes do valor da nota fiscal..
        /// </summary>
        public static string ValorTotalDiferenteValorNotaFiscal {
            get {
                return ResourceManager.GetString("ValorTotalDiferenteValorNotaFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento não pode ser menor que a data de emissão da NF..
        /// </summary>
        public static string VencimentoFormaPagamentoMenorDataEmissaoNF {
            get {
                return ResourceManager.GetString("VencimentoFormaPagamentoMenorDataEmissaoNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento não pode ser menor que a data da EM..
        /// </summary>
        public static string VencimentoFormaPagamentoMenorDataEntradaMaterial {
            get {
                return ResourceManager.GetString("VencimentoFormaPagamentoMenorDataEntradaMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento do imposto não pode ser menor que a data de emissão da NF..
        /// </summary>
        public static string VencimentoImpostoMenorDataEmissaoNF {
            get {
                return ResourceManager.GetString("VencimentoImpostoMenorDataEmissaoNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento do imposto não pode ser menor que a data da EM..
        /// </summary>
        public static string VencimentoImpostoMenorDataEntradaMaterial {
            get {
                return ResourceManager.GetString("VencimentoImpostoMenorDataEntradaMaterial", resourceCulture);
            }
        }
    }
}
